-- ============================================================================
-- imbaptist.org (imfbchurch) — Supabase 초기 설정
-- 새 프로젝트: https://illbgsjvhsciougzjgwn.supabase.co
-- ----------------------------------------------------------------------------
-- 이 Supabase 프로젝트는 다른 2개의 홈페이지와 공유됩니다.
-- 섞이지 않도록 이 홈페이지의 모든 테이블/스토리지는 "imfb_" / "imfb-" 접두사를
-- 사용합니다. 아래 SQL을 Supabase 대시보드 > SQL Editor 에서 1회 실행하세요.
-- (기존 다른 홈페이지의 테이블은 건드리지 않습니다.)
-- ============================================================================

-- ── 1. 테이블 생성 ─────────────────────────────────────────────────────────

-- 사진(hero / gallery / pastor / strategy): type 기준 upsert
create table if not exists public.imfb_photos (
  type text primary key,
  urls text
);

-- 예배 일정
create table if not exists public.imfb_schedule (
  id       bigint generated by default as identity primary key,
  date     text,
  day      text,
  title    text,
  speaker  text,
  time     text,
  location text
);

-- 메인 YouTube
create table if not exists public.imfb_youtube (
  id    bigint generated by default as identity primary key,
  url   text,
  title text
);

-- INTO Worship YouTube
create table if not exists public.imfb_worship_youtube (
  id    bigint generated by default as identity primary key,
  url   text,
  title text
);

-- Sermon YouTube
create table if not exists public.imfb_sermon_youtube (
  id    bigint generated by default as identity primary key,
  url   text,
  title text
);

-- Korean Food Day 사진 (단일 row, id=1 에 urls JSON 저장)
create table if not exists public.imfb_kfd_photos (
  id   bigint primary key,
  urls text
);

-- 교회 정보(목사명/소개/예배시간/주소): key 기준 upsert
create table if not exists public.imfb_church_info (
  key   text primary key,
  value text
);

-- ── 2. RLS 활성화 + anon 접근 정책 ─────────────────────────────────────────
-- 관리자 페이지(admin.html)는 anon 키로 직접 읽기/쓰기 하므로 anon 에 모든
-- 작업을 허용합니다. (이 정책은 imfb_ 테이블에만 적용되어 다른 홈페이지와 무관)

do $$
declare t text;
begin
  foreach t in array array[
    'imfb_photos','imfb_schedule','imfb_youtube','imfb_worship_youtube',
    'imfb_sermon_youtube','imfb_kfd_photos','imfb_church_info'
  ]
  loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('drop policy if exists "imfb_anon_all" on public.%I;', t);
    execute format(
      'create policy "imfb_anon_all" on public.%I for all to anon using (true) with check (true);', t);
  end loop;
end $$;

-- ── 3. 스토리지 버킷 (이미지 업로드) ───────────────────────────────────────
-- 버킷 이름: imfb-church-images (public)
insert into storage.buckets (id, name, public)
values ('imfb-church-images', 'imfb-church-images', true)
on conflict (id) do update set public = true;

-- anon 이 이 버킷에만 업로드/조회/수정 가능하도록 정책 추가
drop policy if exists "imfb_bucket_read"   on storage.objects;
drop policy if exists "imfb_bucket_insert" on storage.objects;
drop policy if exists "imfb_bucket_update" on storage.objects;

create policy "imfb_bucket_read" on storage.objects
  for select to anon using (bucket_id = 'imfb-church-images');

create policy "imfb_bucket_insert" on storage.objects
  for insert to anon with check (bucket_id = 'imfb-church-images');

create policy "imfb_bucket_update" on storage.objects
  for update to anon
  using (bucket_id = 'imfb-church-images')
  with check (bucket_id = 'imfb-church-images');

-- 완료. 이제 imbaptist.org 가 새 Supabase 프로젝트를 사용합니다.
